# Generated by Django 4.1.5 on 2023-01-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_productline_order_productimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productimage",
            old_name="alternative",
            new_name="alternative_text",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="name",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.ImageField(default="test.jpg", upload_to=None),
        ),
    ]
